# *******************************************************************************
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Gitlint check
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  lint-commits:
    name: check-commit-messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Gitlint Action
        if: ${{ github.event_name == 'pull_request' }}
        uses: ./.github/actions/gitlint
        with:
          pr-number: ${{ github.event.number }}
          base-branch: ${{ github.event.pull_request.base.ref }}
  clang-tidy:
    name: Clang-Tidy Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Clang
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-16 clang-tidy-16
          sudo apt-get install -y build-essential libc++-dev libc++abi-dev
      - name: Set up Bazel
        run: |
          wget https://github.com/bazelbuild/bazelisk/releases/download/v1.12.0/bazelisk-linux-amd64
          chmod +x bazelisk-linux-amd64
          sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel
      - name: Run Bazel Build
        run: bazel run refresh_compile_commands
      - name: Run Clang-Tidy
        run: |
          find . -name '*.cpp' -print0 | xargs -0 clang-tidy /workspaces/inc_json_p/compile_commands.json --fix-errors -checks='*'
